### ISSUE TITLE
As soon as i click generate segments i get an error and nothing happens for like 1h

### ISSUE THREAD

**Issue by Slowing4356** [Flowtter/crispy#53]
This is what i get, shown in the browser console.
![image](https://github.com/user-attachments/assets/17040c0d-5b13-4f21-86ec-f735d4e2b2ad)

My whole logs from cmd.

```
C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\detection.py:78: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  net.load_state_dict(copyStateDict(torch.load(trained_model, map_location=device)))
C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\recognition.py:169: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(model_path, map_location=device)
INFO:     Started server process [9932]
INFO:     Waiting for application startup.
INFO:     Adding highlight 0726(1).mp4
INFO:     Adding highlight 0726(10).mp4
INFO:     Adding highlight 0726(11).mp4
INFO:     Adding highlight 0726(12).mp4
INFO:     Adding highlight 0726(2).mp4
INFO:     Adding highlight 0726(3).mp4
INFO:     Adding highlight 0726(4).mp4
INFO:     Adding highlight 0726(5).mp4
INFO:     Adding highlight 0726(6).mp4
INFO:     Adding highlight 0726(7).mp4
INFO:     Adding highlight 0726(8).mp4
INFO:     Adding highlight 0726(9).mp4
INFO:     Adding highlight 0726.mp4
INFO:     Adding 13 highlights, this may take a while.
WARNING:  Wait for `Application startup complete.` to use Crispy.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7821 (Press CTRL+C to quit)
INFO:     127.0.0.1:62040 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /highlights/66a37fc99230e9d45b721291/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fc99230e9d45b721293/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fca9230e9d45b721295/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /highlights/66a37fca9230e9d45b72129d/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fcb9230e9d45b72129f/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fca9230e9d45b721297/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fca9230e9d45b721299/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fcb9230e9d45b7212a1/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fca9230e9d45b72129b/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /highlights/66a37fcb9230e9d45b7212a3/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fcb9230e9d45b7212a5/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fcb9230e9d45b7212a7/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fcb9230e9d45b7212a9/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fc99230e9d45b721291 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /filters/66a37fc99230e9d45b721291 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fc99230e9d45b721293 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fc99230e9d45b721293 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fca9230e9d45b721295 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /filters/66a37fca9230e9d45b721295 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62046 - "GET /highlights/66a37fc99230e9d45b721291/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fca9230e9d45b721297 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /filters/66a37fca9230e9d45b721297 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fca9230e9d45b721299 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fca9230e9d45b721299 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fca9230e9d45b72129b HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /filters/66a37fca9230e9d45b72129b HTTP/1.1" 200 OK
INFO:     127.0.0.1:62047 - "GET /highlights/66a37fc99230e9d45b721293/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62048 - "GET /highlights/66a37fca9230e9d45b721295/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fca9230e9d45b72129d HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /filters/66a37fca9230e9d45b72129d HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fcb9230e9d45b72129f HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fcb9230e9d45b72129f HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fcb9230e9d45b7212a1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /filters/66a37fcb9230e9d45b7212a1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62049 - "GET /highlights/66a37fca9230e9d45b721297/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62050 - "GET /highlights/66a37fca9230e9d45b721299/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62051 - "GET /highlights/66a37fca9230e9d45b72129b/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fcb9230e9d45b7212a3 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /filters/66a37fcb9230e9d45b7212a3 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fcb9230e9d45b7212a5 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fcb9230e9d45b7212a5 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fcb9230e9d45b7212a7 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /filters/66a37fcb9230e9d45b7212a7 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fcb9230e9d45b7212a9 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /filters/66a37fcb9230e9d45b7212a9 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62046 - "GET /highlights/66a37fcb9230e9d45b7212a7/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62051 - "GET /highlights/66a37fcb9230e9d45b7212a3/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62049 - "GET /highlights/66a37fcb9230e9d45b7212a5/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62047 - "GET /highlights/66a37fca9230e9d45b72129d/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62048 - "GET /highlights/66a37fcb9230e9d45b7212a1/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62050 - "GET /highlights/66a37fcb9230e9d45b72129f/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62046 - "GET /highlights/66a37fcb9230e9d45b7212a9/thumbnail HTTP/1.1" 200 OK
INFO:     127.0.0.1:62051 - "GET /highlights/66a37fc99230e9d45b721291/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62047 - "GET /highlights/66a37fca9230e9d45b721297/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62048 - "GET /highlights/66a37fca9230e9d45b721295/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62049 - "GET /highlights/66a37fc99230e9d45b721293/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62050 - "GET /highlights/66a37fca9230e9d45b721299/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62046 - "GET /highlights/66a37fca9230e9d45b72129b/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62049 - "GET /highlights/66a37fca9230e9d45b72129d/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62050 - "GET /highlights/66a37fcb9230e9d45b72129f/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62047 - "GET /highlights/66a37fcb9230e9d45b7212a1/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62051 - "GET /highlights/66a37fcb9230e9d45b7212a3/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62048 - "GET /highlights/66a37fcb9230e9d45b7212a5/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62046 - "GET /highlights/66a37fcb9230e9d45b7212a7/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62049 - "GET /highlights/66a37fcb9230e9d45b7212a9/snippet HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fc99230e9d45b721291/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fc99230e9d45b721293/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fca9230e9d45b721295/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /highlights/66a37fca9230e9d45b721297/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fca9230e9d45b721299/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fca9230e9d45b72129b/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fca9230e9d45b72129d/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fcb9230e9d45b72129f/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fcb9230e9d45b7212a1/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /highlights/66a37fcb9230e9d45b7212a3/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fcb9230e9d45b7212a5/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fcb9230e9d45b7212a7/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fcb9230e9d45b7212a9/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /musics HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /musics/66a37fc99230e9d45b721290 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62049 - "GET /musics/66a37fc99230e9d45b721290/music HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fc99230e9d45b721291/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fc99230e9d45b721293/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fca9230e9d45b721295/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /highlights/66a37fca9230e9d45b721297/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fca9230e9d45b721299/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fca9230e9d45b72129b/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fca9230e9d45b72129d/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /highlights/66a37fcb9230e9d45b72129f/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fcb9230e9d45b7212a1/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /highlights/66a37fcb9230e9d45b7212a3/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fcb9230e9d45b7212a5/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fcb9230e9d45b7212a7/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fcb9230e9d45b7212a9/segments HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /filters/global HTTP/1.1" 200 OK
INFO:     127.0.0.1:62046 - "GET /results/thumbnail?t=1721991531182 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62051 - "GET /results/video?t=1721991531182 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\responses.py", line 299, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'merged.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 64, in app
    await response(scope, receive, send)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\responses.py", line 302, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path merged.mp4 does not exist.
INFO:     127.0.0.1:62041 - "GET /highlights HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fc99230e9d45b721291 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /filters/66a37fc99230e9d45b721291 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fc99230e9d45b721293 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fc99230e9d45b721293 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fca9230e9d45b721295 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /filters/66a37fca9230e9d45b721295 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fca9230e9d45b721297 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /filters/66a37fca9230e9d45b721297 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fca9230e9d45b721299 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fca9230e9d45b721299 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fca9230e9d45b72129b HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /filters/66a37fca9230e9d45b72129b HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fca9230e9d45b72129d HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /filters/66a37fca9230e9d45b72129d HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /highlights/66a37fcb9230e9d45b72129f HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fcb9230e9d45b72129f HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fcb9230e9d45b7212a1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /filters/66a37fcb9230e9d45b7212a1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fcb9230e9d45b7212a3 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fcb9230e9d45b7212a3 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62043 - "GET /highlights/66a37fcb9230e9d45b7212a5 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62045 - "GET /filters/66a37fcb9230e9d45b7212a5 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62042 - "GET /highlights/66a37fcb9230e9d45b7212a7 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62044 - "GET /filters/66a37fcb9230e9d45b7212a7 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/66a37fcb9230e9d45b7212a9 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /filters/66a37fcb9230e9d45b7212a9 HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "POST /highlights/segments/generate HTTP/1.1" 200 OK
INFO:     127.0.0.1:62041 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62040 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62070 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62071 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62071 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62071 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62071 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62095 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62158 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62158 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62159 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62169 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62179 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62179 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62180 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62180 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62197 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62198 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62210 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62211 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62217 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62217 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62226 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62227 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62237 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:62238 - "GET /highlights/segments/generate/status HTTP/1.1" 200 OK
```

**Comment by Flowtter** [comment]
Hi,

That is surprising, I've never seen this before, it seems like the final montage is not generated, probably a complex combination of filters and music, and I'd be interested to have more info.

Can you take a short recording where you go through all the pages inside crispy ? So I can see your configuration, and then try to re-run the processing of the highlights, and then the final montage ?

What game are you using ?

**Comment by Slowing4356** [comment]
> Hi,
> 
> That is surprising, I've never seen this before, it seems like the final montage is not generated, probably a complex combination of filters and music, and I'd be interested to have more info.
> 
> Can you take a short recording where you go through all the pages inside crispy ? So I can see your configuration, and then try to re-run the processing of the highlights, and then the final montage ?
> 
> What game are you using ?

Okay, so first of all im using the game Overwatch, and im using a 3 minute music without any filters turned on, should the final montage even be generated when i generate segments?

**Comment by Slowing4356** [comment]
And it turns out, after i refresh the page and go to segments, every segment generates after some time.

**Comment by Flowtter** [comment]
Yes you need to generate the segment, and you'll at some point receive a message saying it is ready to generate the final montage !

**Comment by Slowing4356** [comment]
Also, can the generation not work correct if i have some overlay on?

**Comment by Flowtter** [comment]
Shouldn't be an issue, the generation can take some time, just let it run in the background if needed
